name: "Versioning Check"
description: "Determines if a package is ready to be published"
outputs:
  run_publish:
    description: "Boolean on if a new version is ready to be uploaded"
    value: ${{ steps.check_publish.outputs.run_publish }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Versioning Precheck
      id: check_publish
      shell: bash
      run: |
        pkgName=$(cat package.json | jq -r ".name");
        publishedVersion=$(curl "https://registry.npmjs.org/${pkgName}/latest" | jq -r ".version" && echo || echo "0.0.0");
        currentVersion=$(cat package.json | jq -r ".version");
        echo "Package: $pkgName";
        echo "Published: $publishedVersion";
        echo "Current: $currentVersion";
        if [ "$publishedVersion" = "$currentVersion" ]
        then
            echo "Publish: false"
            echo "::set-output name=run_publish::false"
        else
            echo "Publish: true"
            echo "::set-output name=run_publish::true"
        fi