name: "Publish Package"
description: "Uploads a package to the NPM and GitHub Packages Registry"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup NPM Registry
      uses: actions/setup-node@v2
      with:
        registry-url: 'https://registry.npmjs.org'
    - name: Install Dependencies
      run: npm install
    - name: Publish to NPM
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Setup Github Registry
      uses: actions/setup-node@v2
      with:
        registry-url: 'https://npm.pkg.github.com'
    - name: Publish to GitHub Packages
      run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}